export interface SurveyRecord {
    conocimiento_nightsale: string; // ¿Has escuchado...
    dia_conocimiento: string; // Según tu conocimiento...
    compra_nightsale: string; // ¿Has comprado...
    frecuencia_compra: string; // ¿Con qué frecuencia...
    canal_compra: string; // ¿Por cuál de estos canales...
    satisfaccion_compra: string; // ¿Cómo calificarías...
    recomendacion: string; // Del 1 al 5...
    razon_no_compra: string; // ¿Por qué no has comprado...
    ciudad: string;
}

export type City = 'Quito' | 'Guayaquil' | 'General';
